### ISSUE TITLE
Netopeer crashes by get / get-config request

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/Netopeer2#1]
Netopeer crashes by get / get-config request. Logs + backtrace:

```
netopeer2-server[17615]: Session 1: received message:
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <get/>
</rpc>
netopeer2-server[17615]: DICT: inserting "rpc" with collision 
netopeer2-server[17615]: DICT: inserting "message-id" with collision 
netopeer2-server[17615]: DICT: inserting "101" with collision 
netopeer2-server[17615]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[17615]: DICT: inserting (refcount) "get"
netopeer2-server[17615]: DICT: inserting (refcount) ""
netopeer2-server[17615]: DICT: inserting (refcount) ""

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4fce700 (LWP 17616)]
0x00007ffff7965fd5 in lys_parent (node=0x63f648) at /home/rasto/libraries/libyang/src/tree_schema.c:2854
2854	    if (node->parent->nodetype == LYS_AUGMENT) {
(gdb) bt
#0  0x00007ffff7965fd5 in lys_parent (node=0x63f648) at /home/rasto/libraries/libyang/src/tree_schema.c:2854
#1  0x00007ffff795e986 in ly_check_mandatory (data=0x7fffec0017d0, schema=0x640920, status=1) at /home/rasto/libraries/libyang/src/tree_schema.c:594
#2  0x00007ffff7966350 in lyd_check_topmandatory (data=0x7fffec0017d0, ctx=0x6212c0, rpc=0x0, options=528) at /home/rasto/libraries/libyang/src/tree_data.c:88
#3  0x00007ffff79400f1 in lyd_parse_xml (ctx=0x6212c0, root=0x7fffec0008d8, options=528) at /home/rasto/libraries/libyang/src/parser_xml.c:562
#4  0x00007ffff76f27ae in nc_recv_rpc (session=0x670f90, rpc=0x7ffff4fcde88) at /home/rasto/libraries/libnetconf2/src/session_server.c:820
#5  0x00007ffff76f2fa5 in nc_ps_poll (ps=0x670600, timeout=500) at /home/rasto/libraries/libnetconf2/src/session_server.c:1039
#6  0x0000000000404211 in process_loop (arg=0x0) at /home/rasto/libraries/Netopeer2/server/main.c:382
#7  0x00007ffff7bc4182 in start_thread (arg=0x7ffff4fce700) at pthread_create.c:312
#8  0x00007ffff71c847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

List of modules installed in sysrepo (minimal set required by Netopeer + turing-machine):
```
Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
turing-machine                | 2013-12-27 | root:root           | 644         |                               |
ietf-netconf-monitoring       | 2010-10-04 | root:root           | 644         |                               |
ietf-netconf-acm              | 2012-02-22 |                     |             |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 644         |                               |
ietf-netconf-with-defaults    | 2011-06-01 | root:root           | 644         |                               |
```

**Comment by michalvasko** [comment]
Hi,
please try it now again, with the current master branches of all libyang, libnetconf2, and netopeer2-server. It works for me now because we added many bugfixes mainly to libyang, but I may have missed something.

Regards,
Michal

**Comment by rastislavszabo** [comment]
works correctly now, I'm closing the issue
