### ISSUE TITLE
netopeer2-server crash during create-subs RPC

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#1051]
netopeer version 2.0.25

here client was doing below create-subscription

Core file and netconf binaries are attached [here](https://github.com/CESNET/netopeer2/files/7446977/netopeer-server-crash.tar.gz)

#### RPC XML
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1635330982915">
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
<stream>NETCONF</stream>
<filter>
<some-notif-name xmlns="urn:some-module"/>
</filter>
<startTime>2021-10-27T15:30:38Z</startTime>
</create-subscription>
</rpc>
```

#### back-trace
```
#0  0x00007f80a84fbfd6 in __strcmp_sse42 () from /usr/lib64/libc.so.6
#1  0x0000000000409413 in np2srv_err_reply_sr (err_info=0x7f808c000ba0)
    at /home/netconf/netopeer2/src/main.c:260
#2  0x00000000004096e9 in np2srv_rpc_cb (rpc=0x7f808c002ed0, ncs=0x8386f0)
    at /home/netconf/netopeer2/src/main.c:337
#3  0x00007f80a943e447 in nc_ps_poll ()
   from /home/netconf/bin/du/usr/local/lib64/libnetconf2.so.2.1.11
#4  0x000000000040bc3a in worker_thread (arg=0x7d1c00)
    at /home/netconf/netopeer2/src/main.c:911
#5  0x00007f80a8cf5ea5 in start_thread () from /usr/lib64/libpthread.so.0
#6  0x00007f80a84bbb0d in epoll_pwait () from /usr/lib64/libc.so.6
#7  0x0000000000000000 in ?? ()
```
```
#1  0x0000000000409413 in np2srv_err_reply_sr (err_info=0x7f808c000ba0)
    at /home/gy1005/repo5g/gy1005_netconf2.0_onecell5g/ran_3rdparty/open_source/netconf/netopeer2/src/main.c:260
260	        if (err_info->err[i].error_format && !strcmp(err_info->err[i].error_format, "NETCONF")) {
(gdb) p i
$42 = 0
(gdb) p err_info->err[0]
$44 = {err_code = SR_ERR_INVAL_ARG, message = 0x7f808c0008f0 "Invalid argument", 
  error_format = 0xffffffff8c000bc0 <Address 0xffffffff8c000bc0 out of bounds>, error_data = 0x7f808c0009c0}
(gdb) p err_info->err[1]
$45 = {err_code = SR_ERR_CALLBACK_FAILED, message = 0x7f808c000ac0 "User callback failed.", error_format = 0x0, error_data = 0x0}
(gdb) 
```

**Comment by michalvasko** [comment]
There is not much information to help me with locating the problem, these errors pass many functions and even SHM segments so I need to determine where exactly some invalid value was read/written. So I would probably need the exact steps to reproduce it but it is also possible that this has already been fixed. You are not using any specific release so it would be best if you could update to 2.0.30 with all the dependencies (should not be a problem) and try again.
