### ISSUE TITLE
Leak in `np2srv_rpc_cb`

### ISSUE THREAD

**Issue by syyyr** [CESNET/netopeer2#1055]
Hi, ASan found this memory leak in Netopeer2:
```
=================================================================
==10709==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 2 object(s) allocated from:
    #0 0x5643311ad321 in calloc (/opt/cesnet-au/Netopeer2/bin/netopeer2-server+0x10b321)
    #1 0x7fd81d3a11fb in lyb_new_node /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_lyb.c
    #2 0x7fd81d398565 in lyb_parse_subtree /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_lyb.c:1048:12
    #3 0x7fd81d396826 in lyd_parse_lyb /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_lyb.c:1251:21
    #4 0x7fd81d57283d in lyd_parse_ /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:970:18
    #5 0x7fd81d51c74f in lyd_parse_data_ /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:1039:12
    #6 0x7fd81d51c272 in lyd_parse_mem /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:1051:14
    #7 0x7fd81cd11e6a in sr_shmsub_rpc_notify /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_sub.c:1821:19
    #8 0x7fd81cb96ffe in sr_rpc_send_tree /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:4005:21
    #9 0x5643311eea0b in np2srv_rpc_cb /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:448:10
    #10 0x7fd81dbebc71 in nc_server_send_reply_io /home/vk/git/netconf-cli/submodules/dependencies/libnetconf2/src/session_server.c:1388:19
    #11 0x7fd81dbebc71 in nc_ps_poll /home/vk/git/netconf-cli/submodules/dependencies/libnetconf2/src/session_server.c:1743:20
    #12 0x5643311eb337 in worker_thread /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:990:14
    #13 0x7fd81ca4e258 in start_thread (/usr/lib/libpthread.so.0+0x9258)

SUMMARY: AddressSanitizer: 144 byte(s) leaked in 2 allocation(s).
```
I'm not really sure when this happens, it seems that it is quite random (only happens sometimes), so I don't have a clear reproducer. I'll look into it later, if needed.

**Comment by syyyr** [comment]
Hmm, this is actually for the libyang1 version of Netopeer... so this issue might be invalid. Oops!
