### ISSUE TITLE
Undefined behavior and leak when doing edit-data 

### ISSUE THREAD

**Issue by syyyr** [CESNET/netopeer2#1060]
Hi, UBSan found this kind of error. It seems to only happen when NACM is enabled.
```
[INF]: SR: Published event "rpc" "/ietf-netconf-nmda:edit-data" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf-nmda:edit-data" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
/home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3107:5: runtime error: store to misaligned address 0x604000066de1 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x604000066de1: note: pointer points here
 63 6f 6c  00 be be be be be be be  be be be be be be be be  be be be 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3107:5 in 
/home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3072:35: runtime error: load of misaligned address 0x604000066de1 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x604000066de1: note: pointer points here
 63 6f 6c  00 0e 00 00 00 61 63 63  65 73 73 2d 64 65 6e 69  65 64 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3072:35 in 
[ERR]: SR: Diff check callback failed (Operation not authorized).
[ERR]: SR: User callback failed.
[INF]: SR: Failed processing of "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: Diff check callback failed (Operation not authorized).
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
/home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3135:31: runtime error: load of misaligned address 0x60f00005fff1 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x60f00005fff1: note: pointer points here
 63 6f 6c  00 0e 00 00 00 61 63 63  65 73 73 2d 64 65 6e 69  65 64 00 5c 00 00 00 41  63 63 65 73 73
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3135:31 in 
```

**Comment by syyyr** [comment]
Also this kind of leak happens when deleting a non-existing leaf:
```
==191141==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x55cbb8366551 in calloc (/opt/cesnet-au/Netopeer2/bin/netopeer2-server+0x123551)
    #1 0x7faa3a14d6f1 in lyd_create_meta /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:2892:10
    #2 0x7faa3a14e537 in lyd_new_meta2 /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:1345:12
    #3 0x7faa39bb11cf in sr_edit_diff_find_oper /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/edit_diff.c:1408:26
    #4 0x7faa39b1bcf0 in sr_edit_batch /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:2225:14
    #5 0x55cbb83d5bf8 in np2srv_rpc_editdata_cb /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/netconf_nmda.c:315:10
    #6 0x7faa39c5173a in sr_shmsub_rpc_listen_call_callback /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_sub.c:2949:21
    #7 0x7faa39c4e448 in sr_shmsub_rpc_listen_process_rpc_events /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_sub.c:3234:25
    #8 0x7faa39b25104 in sr_subscription_process_events /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:3240:25
    #9 0x7faa39b25a2a in sr_process_events /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:3294:10
    #10 0x7faa39c57a01 in sr_shmsub_listen_thread /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_sub.c:3627:15
    #11 0x7faa399f7258 in start_thread (/usr/lib/libpthread.so.0+0x9258)

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x55cbb8366399 in malloc (/opt/cesnet-au/Netopeer2/bin/netopeer2-server+0x123399)
    #1 0x7faa3a0e2ceb in dict_insert /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/hash_table.c:243:28
    #2 0x7faa3a0e4a34 in lydict_insert /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/hash_table.c:282:14
    #3 0x7faa3a33acc8 in parse_ext /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:932:9
    #4 0x7faa3a36d633 in parse_module /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:4287:13
    #5 0x7faa3a37cbb6 in yang_parse_module /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:4671:11
    #6 0x7faa3a2d6ef1 in lys_parse_in /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_schema.c:1573:15
    #7 0x7faa3a125ed8 in ly_ctx_new /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/context.c:295:9
    #8 0x7faa39b624b5 in sr_ly_ctx_new /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:1558:12
    #9 0x7faa39bfed4b in sr_shmmain_ly_ctx_init /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_main.c:432:21
    #10 0x7faa39b02457 in sr_conn_new /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:72:21
    #11 0x7faa39b02457 in sr_connect /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:173:21
    #12 0x55cbb839ed76 in server_init /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:542:10
    #13 0x55cbb839ed76 in main /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:1307:9
    #14 0x7faa396e3b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x55cbb8366399 in malloc (/opt/cesnet-au/Netopeer2/bin/netopeer2-server+0x123399)
    #1 0x7faa3a0e2ceb in dict_insert /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/hash_table.c:243:28
    #2 0x7faa3a0e4a34 in lydict_insert /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/hash_table.c:282:14
    #3 0x7faa3a37e031 in parse_ext_substmt /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:884:9
    #4 0x7faa3a37e1f2 in parse_ext_substmt /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:892:9
    #5 0x7faa3a33af20 in parse_ext /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:943:9
    #6 0x7faa3a36d633 in parse_module /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:4287:13
    #7 0x7faa3a37cbb6 in yang_parse_module /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/parser_yang.c:4671:11
    #8 0x7faa3a2d6ef1 in lys_parse_in /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_schema.c:1573:15
    #9 0x7faa3a125ed8 in ly_ctx_new /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/context.c:295:9
    #10 0x7faa39b624b5 in sr_ly_ctx_new /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:1558:12
    #11 0x7faa39bfed4b in sr_shmmain_ly_ctx_init /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/shm_main.c:432:21
    #12 0x7faa39b02457 in sr_conn_new /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:72:21
    #13 0x7faa39b02457 in sr_connect /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:173:21
    #14 0x55cbb839ed76 in server_init /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:542:10
    #15 0x55cbb839ed76 in main /home/vk/git/netconf-cli/submodules/dependencies/Netopeer2/src/main.c:1307:9
    #16 0x7faa396e3b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)

SUMMARY: AddressSanitizer: 89 byte(s) leaked in 3 allocation(s).
```

Let me know if you need reproducers for these.

**Comment by michalvasko** [comment]
Please try it now (latest *sysrepo*), ideally all the problems should be fixed.

**Comment by syyyr** [comment]
Both errors are fixed, but now I got another error:
```
[INF]: SR: Processing "/ietf-netconf-nmda:edit-data" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
/home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3072:35: runtime error: load of misaligned address 0x604000068de1 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x604000068de1: note: pointer points here
 63 6f 6c  00 0e 00 00 00 61 63 63  65 73 73 2d 64 65 6e 69  65 64 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/common.c:3072:35 in 
[ERR]: SR: Diff check callback failed (Operation not authorized).
[ERR]: SR: User callback failed.
[INF]: SR: Failed processing of "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: Diff check callback failed (Operation not authorized).
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: NP: Session 1: thread 3 event reply error.
```
Again, when doing a basic edit-data operation.

**Comment by michalvasko** [comment]
Missed that one, should be fine now.

**Comment by syyyr** [comment]
It works, thanks.
