### ISSUE TITLE
netopeer2-server crash when 'callhome' connection is closed with multiple yang-push subscriptions

### ISSUE THREAD

**Issue by barbarost** [CESNET/netopeer2#1195]
This is with top of `devel` branches for `netopeer2`, `libnetconf2`, `sysrepo`, and `libyang` (as of 04/19/22):

Steps to reproduce:

1. Startup ODL/lighty.io NETCONF client listening for "callhome" connections (SSH)
2. Configure `netopeer2-server` for callhome ssh connection and start
3. `netopeer2-server` connects to NETCONF client
4. Establish "multiple" subscriptions for periodic yang-push
5. Stop NETCONF client
6. `netopeer2-server` disconnects from NETCONF client
7. On yang-push period it starts a thread to push message and crashes

Note that the same steps does not cause crash, when there is only single yang-push subscription.

Here is the crash dump of `netopeer2-server`:
```
(gdb) run
Starting program: /usr/bin/netopeer2-server -d
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f7570794700 (LWP 1358)]
[New Thread 0x7f756ff93700 (LWP 1359)]
[New Thread 0x7f756f792700 (LWP 1360)]
[New Thread 0x7f756ef91700 (LWP 1361)]
[New Thread 0x7f756e790700 (LWP 1362)]
[New Thread 0x7f756df8f700 (LWP 1363)]
[New Thread 0x7f756d78e700 (LWP 1364)]
[New Thread 0x7f756cf8d700 (LWP 1365)]
[New Thread 0x7f7573482780 (LWP 1366)]
[New Thread 0x7f7557fff700 (LWP 1367)]
[Thread 0x7f7557fff700 (LWP 1367) exited]
[New Thread 0x7f7557fff700 (LWP 1368)]
[Thread 0x7f7557fff700 (LWP 1368) exited]
[New Thread 0x7f7557fff700 (LWP 1369)]
[ERR]: LN: Session 1: SSH channel poll error (Socket error: disconnected).
[New Thread 0x7f75577fe700 (LWP 1370)]

Thread 14 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f75577fe700 (LWP 1370)]
0x00007f7572423d28 in sr_errinfo_free (err_info=0x7f756800daa0) at /opt/dev/sysrepo/src/log.c:338
338	        if (((*err_info)->err_count != 1) || ((*err_info)->err[0].err_code != SR_ERR_NO_MEMORY)) {
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007f7572423d28 in sr_errinfo_free (err_info=0x7f756800daa0) at /opt/dev/sysrepo/src/log.c:338
#1  0x00007f7572423401 in sr_api_ret (session=0x7f756800da80, err_info=0x0) at /opt/dev/sysrepo/src/log.c:89
#2  0x00007f75724048bc in sr_session_switch_ds (session=0x7f756800da80, ds=SR_DS_OPERATIONAL) at /opt/dev/sysrepo/src/sysrepo.c:861
#3  0x00005617c8c1c733 in yang_push_notif_update_send (ncs=0x7f7568000bd0, yp_data=0x7f7564002c00, nc_sub_id=2) at /opt/dev/Netopeer2/src/yang_push.c:865
#4  0x00005617c8c1c92e in yang_push_update_timer_cb (sval=...) at /opt/dev/Netopeer2/src/yang_push.c:920
#5  0x00007f75730d4467 in timer_sigev_thread (arg=0x7f7550000c80) at ../sysdeps/unix/sysv/linux/timer_routines.c:62
#6  0x00007f75729ed6db in start_thread (arg=0x7f75577fe700) at pthread_create.c:463
#7  0x00007f757212b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) p *err_info
$1 = (sr_error_info_t *) 0x20
(gdb) up
#1  0x00007f7572423401 in sr_api_ret (session=0x7f756800da80, err_info=0x0) at /opt/dev/sysrepo/src/log.c:89
89	        sr_errinfo_free(&session->err_info);
(gdb) up
#2  0x00007f75724048bc in sr_session_switch_ds (session=0x7f756800da80, ds=SR_DS_OPERATIONAL) at /opt/dev/sysrepo/src/sysrepo.c:861
861	    return sr_api_ret(session, err_info);
(gdb) p *session
$2 = {conn = 0x0, ds = SR_DS_OPERATIONAL, sid = 0, user = 0x7f7568007d10 "", nacm_user = 0x7f75680092f0 "", err_info = 0x20, orig_name = 0x74 <error: Cannot access memory at address 0x74>, orig_data = 0x7f756800c3f0, ev = 1744832720, ev_data = {
    orig_name = 0x7f7568002a70 "\200\331", orig_data = 0x7f756800d670}, ev_error = {message = 0x7f756800bcb0 "\020\256", format = 0x0, data = 0x0}, ptr_lock = pthread_mutex_t = {Type = Recursive, Status = Not acquired, Robust = No, Shared = No, Protocol = None}, 
  subscriptions = 0x0, subscription_count = 33, dt = {{edit = 0x7f756800dce0, diff = 0x7f7568002b50}, {edit = 0x20, diff = 0x24}, {edit = 0x7f756800c4c0, diff = 0x7f75680008d0}, {edit = 0x0, diff = 0x75}}, notif_buf = {thread_running = 0, tid = 5483655329742891, lock = {
      mutex = pthread_mutex_t = {Type = Normal, Status = Not acquired, Robust = No, Shared = No, Protocol = None}, cond = pthread_cond_t = {Threads known to still execute a wait function = 0, Clock ID = CLOCK_REALTIME, Shared = No}, r_mutex = pthread_mutex_t = {
        Type = Normal, Status = Acquired, possibly with no waiters, Owner ID = 149, Robust = Yes, Shared = Yes, Protocol = Priority protect, Priority ceiling = 0}, readers = {1744885216, 32629, 0, 0, 0, 0, 0, 0, 3402617232, 22039}, 
      read_count = "\000\000\000\000\000\000\000\000\320d", upgr = 22039, writer = 1744844928}, first = 0x300000101, last = 0x7f7568008be0}}
(gdb) up
#3  0x00005617c8c1c733 in yang_push_notif_update_send (ncs=0x7f7568000bd0, yp_data=0x7f7564002c00, nc_sub_id=2) at /opt/dev/Netopeer2/src/yang_push.c:865
865	    sr_session_switch_ds(user_sess->sess, yp_data->datastore);
(gdb) p *user_sess
$3 = {sess = 0x7f756800da80, ref_count = 1}
```

**Comment by michalvasko** [comment]
Yes, a problem with freeing all the subscriptions, should work now.
