### ISSUE TITLE
TLS configuration query, generated keys

### ISSUE THREAD

**Issue by nicholasthorn** [CESNET/netopeer2#1459]
Hello,

Firstly, thanks for the excellent software & support!

I have a query about TLS configuration; I have searched through the issues / read the documentation and it didn't quite explain it - perhaps you can point me at some.  

We are updating from the legacy branch to the latest version of sysrepo/netopeer stack.  We had TLS working fine with legacy branch & our own generated private-key & server certificates - however on the new version as the yang models have changed it's not quite clear what to populate the keystore/asymmetric-keys/asymmetric-key/public-key node with?  

In the example config this isn't provided; only the server cert.  To my understanding this contains the public-key - is this correct?  What do you suggest populating the public-key node with?  If there are any good resources you could recommend on TLS they would be appreciated too.

Thanks!

**Comment by michalvasko** [comment]
[This](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-netconf-client-server-14) should be the draft of the YANG modules being used, all the information about them should be there. Also, if you are looking for examples, look at this [README](https://github.com/CESNET/netopeer2/#tls-listen) section.

**Comment by nicholasthorn** [comment]
Thanks - yes, the example doesn't answer the question though, as the server public-key in the example doesn't map to any of the supplied keys or certificates that I can see.  So it isn't clear where it comes from.

**Comment by michalvasko** [comment]
In the directory `tls_certs` there are 3 pairs of private keys and the corresponding certificates. The server public key is from the said certificate. I thought it would be obvious.

**Comment by nicholasthorn** [comment]
“A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.” :-)

Thanks Michal, makes sense & I've got that working.

Regarding the client.crt, in the legacy version of netopeer this was not required.  My understanding is that the client cert is provided as part of the TLS handshake - rather than being preloaded into the truststore as in the example.  Is it expected that clients will provide certs to be preloaded like this?

**Comment by michalvasko** [comment]
The server needs to authenticate the client somehow, it can do so based on a trusted certificate, which can be directly the client certificate or any CA certificates in its certificate chain. Not sure how it worked before, some certificate had to be trusted but maybe it was a CA one instead of the peer one.

**Comment by alok1802** [comment]
on my netconf controller (install server certificated copied from netopeer2 example )i am getting below error 

Caused by: javax.net.ssl.SSLProtocolException: Unexpected handshake message: client_hello
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:347)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:294)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:437)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1512)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1390)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	... 17 more

and netopper2 on connect command (passing client certificate & key from example certificate )
gettign error: SSL connect to "some ip" failed (unexpected message)
