### ISSUE TITLE
not able to do handshake

### ISSUE THREAD

**Issue by alok1802** [CESNET/netopeer2#1466]
on my netconf controller (install server certificated copied from netopeer2 example )i am getting below error

Caused by: javax.net.ssl.SSLProtocolException: Unexpected handshake message: client_hello
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:347)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:294)
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:437)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1512)
at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1526)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1390)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
... 17 more

and netopper2 on connect command (passing client certificate & key from example certificate )
gettign error: SSL connect to "some ip" failed (unexpected message)

**Comment by michalvasko** [comment]
So you have only taken the example certificates from *netopeer2* and used them in some other NETCONF Java implementation? Then ask them for help, I am really not able to.
