### ISSUE TITLE
netopeer2-server segfault

### ISSUE THREAD

**Issue by dongyangf** [CESNET/Netopeer2#245]
Core file:
(gdb) bt
#0  0x0000000000415c8e in np2srv_ntf_send ()
#1  0x0000000000415f6e in np2srv_ntf_clb ()
#2  0x00007fe97d15e0e9 in cl_sm_fd_read_data () from /usr/local/lib/libsysrepo.so.0.7
#3  0x00007fe97be95d73 in ?? ()
#4  0x00000000006392d8 in ?? ()
#5  0x00007fe97be993de in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb) q

Log:
2018-05-10T15:04:41.188006+00:00 localhost netopeer2-server[1947]: nc_server_notif_send: invalid argument (session).
2018-05-10T15:04:41.188410+00:00 localhost netopeer2-server[1947]: nc_server_notif_send: invalid argument (session).

**Comment by dongyangf** [comment]
Hi, I think same as #244, Thank you!
