### ISSUE TITLE
Possible DOS: Netopeer2 crashes by incorrect chunking

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/Netopeer2#5]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4f0e700 (LWP 7472)]
0x00007ffff791eadd in lyxml_parse_mem (ctx=0x6281a0, data=0x0, options=0) at /home/rasto/libraries/libyang/src/xml.c:1137
1137	    while (*c) {
(gdb) bt
#0  0x00007ffff791eadd in lyxml_parse_mem (ctx=0x6281a0, data=0x0, options=0) at /home/rasto/libraries/libyang/src/xml.c:1137
#1  0x00007ffff76d9cfd in nc_read_msg (session=0x6ad750, data=0x7ffff4f0de30) at /home/rasto/libraries/libnetconf2/src/io.c:334
#2  0x00007ffff76e9c45 in nc_recv_rpc (session=0x6ad750, rpc=0x7ffff4f0de88) at /home/rasto/libraries/libnetconf2/src/session_server.c:815
#3  0x00007ffff76ea66d in nc_ps_poll (ps=0x6acdc0, timeout=500, session=0x7ffff4f0dec8) at /home/rasto/libraries/libnetconf2/src/session_server.c:1080
#4  0x000000000040537b in process_loop (arg=0x0) at /home/rasto/libraries/Netopeer2/server/main.c:422
#5  0x00007ffff7bc4184 in start_thread (arg=0x7ffff4f0e700) at pthread_create.c:312
#6  0x00007ffff718137d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Steps to reproduce: do not insert line feed before the hash character (#) of a new chunk, e.g. after following rpc-reply:

```
#170
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <get-config>
        <source>
            <running/>
        </source>
    </get-config>
</rpc>
##

#149
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"></data></rpc-reply>
##
#170              <----- LF missing before #
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <get-config>
        <source>
            <running/>
        </source>
    </get-config>
</rpc>
##

```

**Comment by michalvasko** [comment]
Hi,
this was a libnetconf2 issue, should be fixed now.

Regards,
Michal
