### ISSUE TITLE
Crash in netopeer2-server when handling multiple notification subscribers

### ISSUE THREAD

**Issue by igortern** [CESNET/Netopeer2#536]
- versions: netopeer2-server, sysrepo, libnetconf, libyang from devel
- shm was cleaned before the test

scenario:
1) [local] client1 subscribes to sysrepo notifications 
2) [remote] client2 connect to netopeer2-server and subscribes to notifications
3) netopeer2-server crashes on assertion in shm_main.c.
The backtrace below:
[INF]: LN: Accepted a connection on 0.0.0.0:10830.
[INF]: SR: Session 3 (user "root") created.
[2020/01/23 11:49:22.091880, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/01/23 11:49:22.096749, 2] ssh_server_connection_callback:  SSH client banner: SSH-2.0-SSHD-UNKNOWN
[2020/01/23 11:49:22.096780, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-SSHD-UNKNOWN
[2020/01/23 11:49:22.096922, 2] ssh_kex_select_methods:  Negotiated ecdh-sha2-nistp521,ssh-rsa,aes128-ctr,aes128-ctr,hmac-sha1,hmac-sha1,none,none,,
[2020/01/23 11:49:22.141165, 2] ssh_packet_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2020/01/23 11:49:22.141384, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2020/01/23 11:49:22.141403, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2020/01/23 11:49:22.141456, 2] ssh_packet_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2020/01/23 11:49:22.160649, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[2020/01/23 11:49:22.205089, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "igort" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/01/23 11:49:22.216136, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 4 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 5 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" with ID 1.
[INF]: SR: Processing "operational" "ietf-yang-library" event with ID 1.
[INF]: SR: Finished processing "operational" event with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 4 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 6 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" with ID 1.
[INF]: SR: Processing "operational" "nc-notifications" event with ID 1.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Finished processing "operational" event with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: SR: Finished processing "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 7 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 3 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 3 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[WRN]: LY: Unable to print anydata content (type 32) as XML.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 8 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[New Thread 0x7ffff1982700 (LWP 30650)]
[ERR]: SR: Internal error (/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:605).
[WRN]: SR: Cleaning up after a non-existent sysrepo client with PID 1852793716.
netopeer2-server: /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1009: sr_shmmain_state_recover: Assertion `shm_lock->write_locked' failed.

Thread 2 "netopeer2-serve" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4988700 (LWP 30556)]
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6d6c801 in __GI_abort () at abort.c:79
#2  0x00007ffff6d5c39a in __assert_fail_base (fmt=0x7ffff6ee37d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff740f931 "shm_lock->write_locked", 
    file=file@entry=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=line@entry=0x3f1, 
    function=function@entry=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:92
#3  0x00007ffff6d5c412 in __GI___assert_fail (assertion=0x7ffff740f931 "shm_lock->write_locked", 
    file=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=0x3f1, 
    function=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:101
#4  0x00007ffff73f7ade in sr_shmmain_state_recover (conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1009
#5  0x00007ffff73fad29 in sr_shmmain_lock_remap (conn=0x61fba0, mode=SR_LOCK_WRITE, remap=0x1, lydmods=0x0, func=0x7ffff740a970 <__func__.9084> "_sr_event_notif_subscribe")
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1964
#6  0x00007ffff73d0f2b in _sr_event_notif_subscribe (session=0x7fffec021670, mod_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x0, tree_callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4338
#7  0x00007ffff73d12b2 in sr_event_notif_subscribe_tree (session=0x7fffec021670, module_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4418
#8  0x000000000040d925 in np2srv_rpc_subscribe_cb (session=0x7ffff4987c40, UNUSED_op_path=0xac7320 "/notifications:create-subscription", input=0x7fffe00012f0, 
    UNUSED_event=SR_EV_RPC, UNUSED_request_id=0x1, UNUSED_output=0x7fffe0000ba0, UNUSED_private_data=0x0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/netopeer2/Netopeer2-devel-server/server/netconf.c:718
#9  0x00007ffff7404cb4 in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x629f70, tmp_sess=0x7ffff4987c40, input_op=0x7fffe00012f0, event=SR_SUB_EV_RPC, request_id=0x1, 
    output_op=0x7ffff4987c18, err_code=0x7ffff4987be4) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2327
#10 0x00007ffff7405701 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x660280, conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2531
#11 0x00007ffff73cceee in sr_process_events (subscription=0x642c20, session=0x0, stop_time_in=0x7ffff4987e20)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:3012
#12 0x00007ffff7406648 in sr_shmsub_listen_thread (arg=0x642c20) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2925
#13 0x00007ffff7bbd6db in start_thread (arg=0x7ffff4988700) at pthread_create.c:463
#14 0x00007ffff6e4d88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6d6c801 in __GI_abort () at abort.c:79
#2  0x00007ffff6d5c39a in __assert_fail_base (fmt=0x7ffff6ee37d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff740f931 "shm_lock->write_locked", 
    file=file@entry=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=line@entry=0x3f1, 
    function=function@entry=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:92
#3  0x00007ffff6d5c412 in __GI___assert_fail (assertion=0x7ffff740f931 "shm_lock->write_locked", 
    file=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=0x3f1, 
    function=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:101
#4  0x00007ffff73f7ade in sr_shmmain_state_recover (conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1009
#5  0x00007ffff73fad29 in sr_shmmain_lock_remap (conn=0x61fba0, mode=SR_LOCK_WRITE, remap=0x1, lydmods=0x0, func=0x7ffff740a970 <__func__.9084> "_sr_event_notif_subscribe")
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1964
#6  0x00007ffff73d0f2b in _sr_event_notif_subscribe (session=0x7fffec021670, mod_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x0, tree_callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4338
#7  0x00007ffff73d12b2 in sr_event_notif_subscribe_tree (session=0x7fffec021670, module_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4418
#8  0x000000000040d925 in np2srv_rpc_subscribe_cb (session=0x7ffff4987c40, UNUSED_op_path=0xac7320 "/notifications:create-subscription", input=0x7fffe00012f0, 
    UNUSED_event=SR_EV_RPC, UNUSED_request_id=0x1, UNUSED_output=0x7fffe0000ba0, UNUSED_private_data=0x0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/netopeer2/Netopeer2-devel-server/server/netconf.c:718
#9  0x00007ffff7404cb4 in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x629f70, tmp_sess=0x7ffff4987c40, input_op=0x7fffe00012f0, event=SR_SUB_EV_RPC, request_id=0x1, 
    output_op=0x7ffff4987c18, err_code=0x7ffff4987be4) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2327
#10 0x00007ffff7405701 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x660280, conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2531
#11 0x00007ffff73cceee in sr_process_events (subscription=0x642c20, session=0x0, stop_time_in=0x7ffff4987e20)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:3012
#12 0x00007ffff7406648 in sr_shmsub_listen_thread (arg=0x642c20) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2925
#13 0x00007ffff7bbd6db in start_thread (arg=0x7ffff4988700) at pthread_create.c:463
#14 0x00007ffff6e4d88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 4
#4  0x00007ffff73f7ade in sr_shmmain_state_recover (conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1009
1009	                                assert(shm_lock->write_locked);
(gdb) p shm_lock
$1 = (struct sr_mod_lock_s *) 0x7ffff7fe83c8
(gdb) p *shm_lock
$2 = {lock = {mutex = pthread_mutex_t = {Type = Normal, Status = Acquired, possibly with no waiters, Owner ID = 0x775c, Robust = No, Shared = Yes, Protocol = None}, Python Exception <class 'gdb.error'> There is no member named __wrefs.: 
cond = {
      __data = {__lock = 0x0, __futex = 0x0, __total_seq = 0x0, __wakeup_seq = 0x0, __woken_seq = 0x0, __mutex = 0x100000000, __nwaiters = 0x0, __broadcast_seq = 0x0}, 
      __size = '\000' <repeats 36 times>, "\001\000\000\000\000\000\000\000\000\000\000", __align = 0x0}, readers = 0x0}, write_locked = 0x0, ds_locked = 0x0, sid = {sr = 0x0, 
    nc = 0x0, user = 0x0}, ds_ts = 0x0}
(gdb) p mod_locks[j][k].mode
$3 = SR_LOCK_WRITE
(gdb) p j
$4 = 0xb
(gdb) p k
$5 = 0x1
(gdb)

**Comment by igortern** [comment]
fixing cut&paste problem in the backtrace above
(gdb) 
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6d6c801 in __GI_abort () at abort.c:79
#2  0x00007ffff6d5c39a in __assert_fail_base (fmt=0x7ffff6ee37d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff740f931 "shm_lock->write_locked", 
    file=file@entry=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=line@entry=0x3f1, 
    function=function@entry=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:92
#3  0x00007ffff6d5c412 in __GI___assert_fail (assertion=0x7ffff740f931 "shm_lock->write_locked", 
    file=0x7ffff740f370 "/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c", line=0x3f1, 
    function=0x7ffff7410010 <__PRETTY_FUNCTION__.8440> "sr_shmmain_state_recover") at assert.c:101
#4  0x00007ffff73f7ade in sr_shmmain_state_recover (conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1009
#5  0x00007ffff73fad29 in sr_shmmain_lock_remap (conn=0x61fba0, mode=SR_LOCK_WRITE, remap=0x1, lydmods=0x0, func=0x7ffff740a970 <__func__.9084> "_sr_event_notif_subscribe")
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_main.c:1964
#6  0x00007ffff73d0f2b in _sr_event_notif_subscribe (session=0x7fffec021670, mod_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x0, tree_callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4338
#7  0x00007ffff73d12b2 in sr_event_notif_subscribe_tree (session=0x7fffec021670, module_name=0x638460 "ietf-netconf-notifications", xpath=0x0, start_time=0x0, stop_time=0x0, 
    callback=0x40a792 <np2srv_ntf_new_cb>, private_data=0x7fffec000e30, opts=0x1, subscription=0x61e7e0 <np2srv+32>)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:4418
#8  0x000000000040d925 in np2srv_rpc_subscribe_cb (session=0x7ffff4987c40, UNUSED_op_path=0xac7320 "/notifications:create-subscription", input=0x7fffe00012f0, 
    UNUSED_event=SR_EV_RPC, UNUSED_request_id=0x1, UNUSED_output=0x7fffe0000ba0, UNUSED_private_data=0x0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/netopeer2/Netopeer2-devel-server/server/netconf.c:718
#9  0x00007ffff7404cb4 in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x629f70, tmp_sess=0x7ffff4987c40, input_op=0x7fffe00012f0, event=SR_SUB_EV_RPC, request_id=0x1, 
    output_op=0x7ffff4987c18, err_code=0x7ffff4987be4) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2327
#10 0x00007ffff7405701 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x660280, conn=0x61fba0)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2531
#11 0x00007ffff73cceee in sr_process_events (subscription=0x642c20, session=0x0, stop_time_in=0x7ffff4987e20)
    at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/sysrepo.c:3012
#12 0x00007ffff7406648 in sr_shmsub_listen_thread (arg=0x642c20) at /home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/shm_sub.c:2925
#13 0x00007ffff7bbd6db in start_thread (arg=0x7ffff4988700) at pthread_create.c:463
#14 0x00007ffff6e4d88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by igortern** [comment]
After taking fresh devel snapshots can't reproduce the problem anymore. 
Sorry for false alarm.
Regards,
Igor
