### ISSUE TITLE
netopeer2-server is segfaulting 

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/netopeer2#617]
Ubuntu 18.04
netopeer2-server is 
```
commit 238f1eefd67bfb8c0487e0d6a5979b825bc0098a (HEAD -> devel, origin/devel)
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon May 11 13:35:47 2020 +0200

    VERSION bump to version 1.1.29

```

I use netopeer2-cli to connect
```
> connect --login root
Interactive SSH Authentication
Type your password:
Password: 
> get-data --datastore running
cli_send_recv: Timeout for receiving a reply expired.
> 
```

The netopeer2-server segfaults.  Running in the debugger shows 

```
Thread 2 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff46b8700 (LWP 8737)]
_nss_compat_getpwnam_r (name=0x0, pwd=0x7ffff46b79a0, buffer=0x7fffe001b230 "\240C\001\340\377\177", buflen=1024, errnop=0x7ffff46b8660) at nss_compat/compat-pwd.c:810
810	nss_compat/compat-pwd.c: No such file or directory.
(gdb) bt
#0  _nss_compat_getpwnam_r (name=0x0, pwd=0x7ffff46b79a0, buffer=0x7fffe001b230 "\240C\001\340\377\177", buflen=1024, errnop=0x7ffff46b8660) at nss_compat/compat-pwd.c:810
#1  0x00007ffff6e1995f in __getpwnam_r (name=0x0, resbuf=0x7ffff46b79a0, buffer=0x7fffe001b230 "\240C\001\340\377\177", buflen=1024, result=0x7ffff46b7988) at ../nss/getXXbyYY_r.c:315
#2  0x000055555556a4ab in ncac_getpwnam (user=0x0, uid=0x7ffff46b7a0c, gid=0x0) at /home/brett/git/netconf/Netopeer2/src/netconf_acm.c:792
#3  0x000055555556a60f in ncac_allowed_tree (top_node=0x5555557d48a0, user=0x0) at /home/brett/git/netconf/Netopeer2/src/netconf_acm.c:838
#4  0x000055555556b477 in ncac_check_data_read_filter (data=0x7ffff46b7aa8, user=0x0) at /home/brett/git/netconf/Netopeer2/src/netconf_acm.c:1252
#5  0x000055555556bf8c in np2srv_rpc_getdata_cb (session=0x7ffff46b7c40, UNUSED_op_path=0x55555582b950 "/ietf-netconf-nmda:get-data", input=0x7fffe0001330, UNUSED_event=SR_EV_RPC, UNUSED_request_id=1, 
    output=0x7fffe0001ad0, UNUSED_private_data=0x0) at /home/brett/git/netconf/Netopeer2/src/netconf_nmda.c:227
#6  0x00007ffff716f92d in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x555555847f80, tmp_sess=0x7ffff46b7c40, input_op=0x7fffe0001330, event=SR_SUB_EV_RPC, request_id=1, output_op=0x7ffff46b7c10, 
    err_code=0x7ffff46b7be8) at /home/brett/git/netconf/sysrepo/src/shm_sub.c:2552
#7  0x00007ffff7170598 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x5555558531d0, conn=0x5555557d6bc0) at /home/brett/git/netconf/sysrepo/src/shm_sub.c:2833
#8  0x00007ffff71343b6 in sr_process_events (subscription=0x555555784890, session=0x0, stop_time_in=0x7ffff46b7e20) at /home/brett/git/netconf/sysrepo/src/sysrepo.c:3037
#9  0x00007ffff71713c6 in sr_shmsub_listen_thread (arg=0x555555784890) at /home/brett/git/netconf/sysrepo/src/shm_sub.c:3202
#10 0x00007ffff7bbd6db in start_thread (arg=0x7ffff46b8700) at pthread_create.c:463
#11 0x00007ffff6e5788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by bbergquist0930** [comment]
The error is triggered by this commit in sysrepo 
https://github.com/sysrepo/sysrepo/commit/41c26faa19a06ad82be109af363a21396c65b42e

**Comment by bbergquist0930** [comment]
[patch.txt](https://github.com/CESNET/netopeer2/files/4612885/patch.txt)

I think this patch will fix this.  Basically instead of trying to get the username from the Sysrepo session, it finds the corresponding Netconf session and gets the username from that.

```
diff --git a/src/netconf_nmda.c b/src/netconf_nmda.c
index aa42612..07669b4 100755
--- a/src/netconf_nmda.c
+++ b/src/netconf_nmda.c
@@ -94,6 +94,7 @@ np2srv_rpc_getdata_cb(sr_session_ctx_t *session, const char *UNUSED(op_path), co
 {
     struct lyd_node_leaf_list *leaf;
     struct lyd_node *node, *data_get = NULL;
+    struct nc_session *ncs;
     char **filters = NULL;
     int filter_count = 0, i, rc = SR_ERR_OK;
     uint32_t max_depth = 0;
@@ -102,6 +103,19 @@ np2srv_rpc_getdata_cb(sr_session_ctx_t *session, const char *UNUSED(op_path), co
     NC_WD_MODE nc_wd;
     sr_get_oper_options_t get_opts = 0;
 
+    /* find this NETCONF session */
+    for (i = 0; (ncs = nc_ps_get_session(np2srv.nc_ps, i)); ++i) {
+        if (nc_session_get_id(ncs) == sr_session_get_nc_id(session)) {
+            break;
+        }
+    }
+    if (!ncs) {
+        ERR("Failed to find NETCONF session SID %u.", sr_session_get_nc_id(session));
+        rc = SR_ERR_INTERNAL;
+        goto cleanup;
+    }
+
+
     /* get default value for with-defaults */
     nc_server_get_capab_withdefaults(&nc_wd, NULL);
 
@@ -224,7 +238,7 @@ np2srv_rpc_getdata_cb(sr_session_ctx_t *session, const char *UNUSED(op_path), co
     ly_set_free(nodeset);
 
     /* perform correct NACM filtering */
-    ncac_check_data_read_filter(&data_get, sr_session_get_user(session));
+    ncac_check_data_read_filter(&data_get, nc_session_get_username(ncs));
 
     /* add output */
     node = lyd_new_output_anydata(output, NULL, "data", data_get, LYD_ANYDATA_DATATREE);
```

**Comment by michalvasko** [comment]
Hi,
yes, you are right and I thought I have already changed it this way everywhere, there is even a function for this. But it seems I have missed this one use-case, should work now.

Regards,
Michal

**Comment by bbergquist0930** [comment]
Works correctly now.
