### ISSUE TITLE
netopeer2-server supports very limited host key algorithms for ssh

### ISSUE THREAD

**Issue by tharunprabhu** [CESNET/netopeer2#667]
I'm unable to connect to my netopeer2-server using ncclient because there is no common match in the host key algorithms supported by ncclient and netopeer2-server. I am however able to connect to the server using netopeer2-cli.

This is the error I get when i try to run a simple get_config ncclient script:

```
o handlers could be found for logger "ncclient.transport.ssh"
Traceback (most recent call last):
  File "eg4.py", line 15, in <module>
    hostkey_verify=False,
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 176, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 141, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 331, in connect
    raise SSHError('Negotiation failed: %s' % e)
ncclient.transport.errors.SSHError: Negotiation failed: Incompatible ssh peer (no acceptable host key)
```

This is what I see in the netopeer2 server logs:
```
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 27 (user "root") created.
[2020/06/30 22:16:07.385349, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/06/30 22:16:07.387853, 2] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.1
[2020/06/30 22:16:07.387905, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.1
[2020/06/30 22:16:07.390215, 1] ssh_kex_select_methods:  kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss]
[ERR]: LN: SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss]).
```

How do I configure netopeer2-server to support more host key algorithms?

**Comment by michalvasko** [comment]
Hi,
actually, you need to configure *libssh*, it is completely in its control. It depends on the version you are using but for libssh 0.9.0 and newer you should be fine with editing system-wide configuration files, their exact path is printed by `cmake` if you compile from source. If you have a package, those files should be in `/etc/ssh`.

Regards,
Michal

**Comment by tharunprabhu** [comment]
Reinstalling libssh-dev fixed the issue. Thanks for your help, Michal!
