### ISSUE TITLE
Segfault when executing an action

### ISSUE THREAD

**Issue by immibis** [CESNET/Netopeer2#8]
I sent this to netopeer2, connected to sysrepo, and netopeer2 crashed:
```
<?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
    <capability>conf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
</capabilities>
</hello>]]>]]>


#142
<rpc message-id="103" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><system-shutdown xmlns="urn:ietf:params:xml:ns:yang:ietf-system"/></rpc>
##
```

Log and GDB output:
```
netopeer2-server[2689]: Session 1: received message:
<?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
    <capability>conf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
</capabilities>
</hello>
netopeer2-server[2689]: (cl_request_process:401) Sending session-start request.
netopeer2-server[2689]: (cl_request_process:423) session-start request sent, waiting for response.
netopeer2-server[2689]: (cl_request_process:445) session-start response received, processing.
netopeer2-server[2689]: Session 1: received message:
<rpc message-id="103" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><system-shutdown xmlns="urn:ietf:params:xml:ns:yang:ietf-system"/></rpc>
netopeer2-server[2689]: (cl_request_process:401) Sending rpc request.
netopeer2-server[2689]: (cl_request_process:423) rpc request sent, waiting for response.
netopeer2-server[2689]: (cl_request_process:445) rpc response received, processing.
netopeer2-server[2689]: (sr_rpc_send:2032) Error by processing of the request.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4f06700 (LWP 2693)]
0x000000000040d09d in op_generic (rpc=0x7fffec000980, ncs=0x6b4ce0)
    at /home/mpilka/ietf962/Netopeer2/server/op_generic.c:125
125	    for (i = 0; i < strs->number; i++) {
(gdb) bt
#0  0x000000000040d09d in op_generic (rpc=0x7fffec000980, ncs=0x6b4ce0)
    at /home/mpilka/ietf962/Netopeer2/server/op_generic.c:125
#1  0x00007ffff76e8ec2 in nc_send_reply (session=0x6b4ce0, rpc=0x7fffec001830)
    at /home/mpilka/ietf962/libnetconf2/src/session_server.c:893
#2  0x00007ffff76e9697 in nc_ps_poll (ps=0x6b4310, timeout=500, 
    session=0x7ffff4f05ec8)
    at /home/mpilka/ietf962/libnetconf2/src/session_server.c:1092
#3  0x000000000040535b in process_loop (arg=0x0)
    at /home/mpilka/ietf962/Netopeer2/server/main.c:422
#4  0x00007ffff7bc4182 in start_thread (arg=0x7ffff4f06700)
    at pthread_create.c:312
#5  0x00007ffff718047d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

It may be relevant that this action was not subscribed to in sysrepo.

Core dump: [netopeer2-server.core.zip](https://github.com/CESNET/Netopeer2/files/367743/netopeer2-server.core.zip)

**Comment by michalvasko** [comment]
Hi,
please check that it is fixed, thanks.

Regards,
Michal
