### ISSUE TITLE
Netopeer2 server v2.0.0 seems to send malformed notifications to clients

### ISSUE THREAD

**Issue by wkerndlm** [CESNET/netopeer2#926]
since migrating a Raspberry Pi4 / Ubuntu 20.10 64bit server from v1.1.70 to v2.0.0, notifications sent from application plugins arrive corrupted at the netconf client side with following pattern:
- the first notification arrives with contents as expected, but with an empty notification timestamp and an additional error message by the client regarding some invalid, resp. non-UTF-8 characters
- no further notifications will arrive except error messages, with some clients terminating the ssh connection as a consequence.

1. Netopeer2-cli:
```
notification ()
<switch-pressed xmlns="urn:sysrepo:raspi-blink">
  <led-control-status>false</led-control-status>
</switch-pressed>

> 
ly ERROR: Invalid character 0x9e. (Line number 1.)
> 
nc ERROR: Session 2: received an invalid message (Invalid character 0x9e.)
```
Netopeer2-Log:
```
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: SR: Processing "notif" "raspi-blink" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Processing "notif" "raspi-blink" event with ID 2.
[INF]: SR: Successful processing of "notif" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Processing "notif" "raspi-blink" event with ID 3.
[INF]: SR: Successful processing of "notif" event with ID 3 priority 0 (remaining 0 subscribers).
```
2. netconf-console:
```
netconf> create-subscription raspi-blink
<?xml version='1.0' encoding='UTF-8'?>
<ok xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
netconf> <notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime></eventTime><switch-pressed xmlns="urn:sysrepo:raspi-blink"><led-control-status>false</led-control-status></switch-pressed></notification>

netconf> 
```
Netopeer2-log:
```
[INF]: NP: Generated new event (netconf-session-start).
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: SR: Processing "notif" "raspi-blink" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Processing "notif" "raspi-blink" event with ID 2.
[INF]: SR: Successful processing of "notif" event with ID 2 priority 0 (remaining 0 subscribers).
[2021/06/10 13:06:57.270592, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
[2021/06/10 13:06:57.270720, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
[ERR]: LN: Session 1: SSH channel poll error (Socket error: Connection reset by peer).
[INF]: NP: Session 1: thread 4 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```

3.  Custom client / netconf-client Python library:
```
First session, intentionally terminated after notification: response looks fine except empty eventTime
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime></eventTime><switch-pressed xmlns="urn:sysrepo:raspi-blink"><led-control-status>false</led-control-status></switch-pressed></notification>

[INF]: NP: Generated new event (netconf-session-start).
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 4 event new RPC.
[INF]: SR: Processing "notif" "raspi-blink" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: NP: Session 1: thread 3 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```
Second session fails:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/netconf_client/session.py", line 115, in _recv_loop
    ele = etree.fromstring(msg)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xDE 0xF6 0x93 0xF0, line 1, column 83

[INF]: NP: Generated new event (netconf-session-start).
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: SR: Processing "notif" "raspi-blink" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: NP: Session 1: thread 2 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```
All subsequnt sessions will also fail until netopeer2-server is restarted. Then there will be one notification again, but all other ones failing.

Relevant application plugin snippet:
```C
            if (switch_pressed) {       //notify only "pressed" but not "released" event
              //derive connection context from session context
              ctx = sr_get_context(sr_session_get_connection(sess));
              // read led-control setting from data store
              rc = sr_get_items(sess, "/raspi-blink:gpio-config/switch/led-control", 0, 0, &val, &val_cnt);
              if (rc != SR_ERR_OK) {
                  SRP_LOG_ERR("raspi-blink: 'led-control' state read from datastore failed: %s.", sr_strerror(rc));
              }
              // create the notification
	          rc = lyd_new_path(NULL, ctx, "/raspi-blink:switch-pressed", NULL, 0, &notif);
              if (rc != LY_SUCCESS) {
                SRP_LOG_ERR("raspi-blink: Creating notification failed: %d", rc);
              }
              // add the input value
              if ((rc = lyd_new_path(notif, NULL, "/raspi-blink:switch-pressed/led-control-status", val->data.bool_val ? "true" : "false", 0, 0)) !=LY_SUCCESS) {
                SRP_LOG_ERR("raspi-blink: Creating notification value failed: %d", rc);
              }
              //send notification
              rc = sr_event_notif_send_tree(sess, notif,0,0);
              if (rc != SR_ERR_OK) {
                SRP_LOG_ERR("Raspi-blink: 'Switch-pressed' notification generation failed: %s.", sr_strerror(rc));
              }
              else
                SRP_LOG_DBGMSG("raspi-blink: ‘Switch-pressed’ notification sent.");
              //cleanup
              lyd_free_all(notif);
              sr_free_values(val, val_cnt);
            }
```
The sysrepo log does not contain any SRP_LOG_ERR messages, so the application code should work correctly- as it did with sysrepo v1.1.43 / netopeer2 v1.1.70 

If you need further information, please let me know.

Best regards
Walter

**Comment by michalvasko** [comment]
Please use current `devel` of all the projects, it was already fixed.

**Comment by wkerndlm** [comment]
Thanks a lot Michal! 
I could verify that this issue is solved in the current development branch.
