### ISSUE TITLE
SIGSEGV in lyv_data_content() at validation.c:857

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#973]
yanglint SO 1.10.2
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.130 (SO v5.6.46
netopeer2-server 1.1.73

Hi,

We are getting SIGSEGV in netopeer2-server, please find the backtrace below.
If needed I can print whatever is required from the core dump.
Could you please advise if this a known issue, maybe already fixed?

Ilja.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  lyv_data_content (node=node@entry=0x7fb6981212a0, options=options@entry=278529, unres=unres@entry=0x7fb6980acf10)
    at /usr/src/debug/libyang/1.0.232+gitAUTOINC+e5fa5b55d7-r0/git/src/validation.c:857
 
857                 iff_size = leaf->value.ident->iffeature_size;
[Current thread is 1 (Thread 0x7fb6ada03700 (LWP 1717))]
(gdb) bt
#0  lyv_data_content (node=node@entry=0x7fb6981212a0, options=options@entry=278529, unres=unres@entry=0x7fb6980acf10)
    at /usr/src/debug/libyang/1.0.232+gitAUTOINC+e5fa5b55d7-r0/git/src/validation.c:857
#1  0x0000003c2b49e3b9 in _lyd_validate (node=node@entry=0x7fb6ada02af0, data_tree=0x7fb698124c40,
    ctx=ctx@entry=0x13cea30, modules=modules@entry=0x7fb698059880, mod_count=mod_count@entry=1, diff=0x7fb6ada02a08,
    options=278529) at /usr/src/debug/libyang/1.0.232+gitAUTOINC+e5fa5b55d7-r0/git/src/tree_data.c:5007
#2  0x0000003c2b49ecc4 in lyd_validate_modules (node=node@entry=0x7fb6ada02af0, modules=modules@entry=0x7fb698059880,
    mod_count=1, options=278529) at /usr/src/debug/libyang/1.0.232+gitAUTOINC+e5fa5b55d7-r0/git/src/tree_data.c:5264
#3  0x0000003c2de1f2cd in sr_modinfo_validate (mod_info=mod_info@entry=0x7fb6ada02ae0, mod_state=mod_state@entry=258,
    finish_diff=finish_diff@entry=1) at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/modinfo.c:2043
#4  0x0000003c2de08dc3 in sr_changes_notify_store (mod_info=mod_info@entry=0x7fb6ada02ae0,
    session=session@entry=0x7fb6a002dc30, timeout_ms=timeout_ms@entry=30000,
    cb_err_info=cb_err_info@entry=0x7fb6ada02ac8)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/sysrepo.c:1998
#5  0x0000003c2de0921f in _sr_replace_config (session=session@entry=0x7fb6a002dc30, ly_mod=ly_mod@entry=0x0,
    src_config=src_config@entry=0x7fb6ada02b80, timeout_ms=timeout_ms@entry=30000)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/sysrepo.c:2279
#6  0x0000003c2de0c44a in sr_copy_config (session=session@entry=0x7fb6a002dc30, module_name=module_name@entry=0x0,
    src_datastore=src_datastore@entry=SR_DS_CANDIDATE, timeout_ms=30000, wait=wait@entry=1)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/sysrepo.c:2396
#7  0x000000000040b8f7 in np2srv_rpc_commit_cb (session=session@entry=0x7fb6980cc4f0, UNUSED_op_path=<optimized out>,
    UNUSED_input=UNUSED_input@entry=0x7fb69817df90, event=<optimized out>,
    UNUSED_request_id=UNUSED_request_id@entry=107, UNUSED_output=<optimized out>, UNUSED_private_data=0x0)
    at /usr/src/debug/netopeer2-server/1.1.73+gitAUTOINC+786d82a87c-r0/git/src/netconf.c:814
#8  0x0000003c2de33843 in sr_shmsub_rpc_listen_call_callback (rpc_sub=rpc_sub@entry=0x26b8810,
    ev_sess=0x7fb6980cc4f0, input_op=0x7fb69817df90, event=event@entry=SR_SUB_EV_RPC,
    request_id=request_id@entry=107, output_op=output_op@entry=0x7fb6ada02d68, err_code=0x7fb6ada02d48)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/shm_sub.c:2782
#9  0x0000003c2de381ea in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x26bb9e0, conn=<optimized out>)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/shm_sub.c:3068
#10 0x0000003c2de0ca57 in sr_process_events (subscription=subscription@entry=0x1406730, session=session@entry=0x0,
    stop_time_in=stop_time_in@entry=0x7fb6ada02e48)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/sysrepo.c:2726
#11 0x0000003c2de38f1a in sr_shmsub_listen_thread (arg=0x1406730)
    at /usr/src/debug/sysrepo/1.4.130+gitAUTOINC+b74df81f3d-r0/git/src/shm_sub.c:3467
#12 0x0000003c2a407477 in start_thread (arg=0x7fb6ada03700)
    at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
#13 0x0000003c2a0f23bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 0
#0  lyv_data_content (node=node@entry=0x7fb6981212a0, options=options@entry=278529, unres=unres@entry=0x7fb6980acf10)
    at /usr/src/debug/libyang/1.0.232+gitAUTOINC+e5fa5b55d7-r0/git/src/validation.c:857
857                 iff_size = leaf->value.ident->iffeature_size;
(gdb) p leaf
$1 = (struct lyd_node_leaf_list *) 0x7fb6981212a0
(gdb) p leaf->value
$2 = {​​​​​​​binary = 0x0, bit = 0x0, bln = 0 '\000', dec64 = 0, enm = 0x0, ident = 0x0, instance = 0x0, int8 = 0 '\000',
  int16 = 0, int32 = 0, int64 = 0, leafref = 0x0, string = 0x0, uint8 = 0 '\000', uint16 = 0, uint32 = 0, uint64 = 0,
  ptr = 0x0}​​​​​​​
(gdb) p leaf->value.ident
$3 = (struct lys_ident *) 0x0
(gdb)
```

**Comment by michalvasko** [comment]
No, I do not think this was fixed and looks like a bug. I will probably need the exact steps to reproduce it before I can fix it.

**Comment by iljatab** [comment]
This issue happens during automated test runs.
There may be lot of steps before the SIGSEGV happens.
But it happens pretty often.

**Comment by iljatab** [comment]
One more thing - the configuration includes only OpenConfig models.
