### ISSUE TITLE
SIGSEGV at parser_lyb.c:681 (with libyang2)

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#981]
yanglint 2.0.71
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.34 (SO v6.4.1)
netopeer2-server 2.0.21

Hi,

We are getting SIGSEGV in netopeer2-server, could you please check?
[model.tar.gz](https://github.com/CESNET/netopeer2/files/6953648/model.tar.gz)

Here are the details:

XML file:
```
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<mpls xmlns="http://metaswitch.com/yang/nbu/rsvp-te/201512110000Z">
  <rsvp-te/>
</mpls>
</data
```

Applied as:
```
> edit-config --target running --config=input.xml
```
YANG model attached.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  lyb_parse_schema_hash (lybctx=lybctx@entry=0x7f4f540122d0, sparent=0x0, mod=mod@entry=0x0, snode=snode@entry=0x7f4f72d805b8)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:681
681                 LOGVAL(lybctx->lybctx->ctx, LYVE_REFERENCE, "Failed to find matching hash for a child node"
[Current thread is 1 (Thread 0x7f4f72d81700 (LWP 2920))]
(gdb) set height 0
(gdb) bt
#0  lyb_parse_schema_hash (lybctx=lybctx@entry=0x7f4f540122d0, sparent=0x0, mod=mod@entry=0x0, snode=snode@entry=0x7f4f72d805b8)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:681
#1  0x000000387522f49a in lyb_parse_subtree_r (lybctx=lybctx@entry=0x7f4f540122d0, parent=0x7f4f54002a40, first_p=first_p@entry=0x0, parsed=parsed@entry=0x0)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:787
#2  0x00000038752303af in lyb_parse_subtree_r (lybctx=lybctx@entry=0x7f4f540122d0, parent=parent@entry=0x0, first_p=first_p@entry=0x7f4f72d80958, parsed=parsed@entry=0x0)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:841
#3  0x000000387522f2a0 in _lyd_parse_lyb (ctx=ctx@entry=0x1d9fa30, ext=ext@entry=0x0, parent=parent@entry=0x0, first_p=first_p@entry=0x7f4f72d80958, in=<optimized out>, 
    parse_opts=parse_opts@entry=458752, val_opts=0, int_opts=48, parsed=0x0, lydctx_p=0x7f4f72d80968)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:1116
#4  0x0000003875230431 in lyb_parse_any_content (tree=0x7f4f72d80958, data=<optimized out>, ctx=0x1d9fa30)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:733
#5  lyb_parse_subtree_r (lybctx=lybctx@entry=0x7f4f5402d6f0, parent=0x7f4f5405f2c0, first_p=first_p@entry=0x0, parsed=parsed@entry=0x0)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:901
#6  0x000000387522fd36 in lyb_parse_subtree_r (lybctx=lybctx@entry=0x7f4f5402d6f0, parent=parent@entry=0x0, first_p=first_p@entry=0x7f4f72d80bd0, 
    parsed=parsed@entry=0x7f4f72d80be0) at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:866
#7  0x000000387522f2a0 in _lyd_parse_lyb (ctx=0x1d9fa30, ext=<optimized out>, parent=0x0, first_p=0x7f4f72d80bd0, in=<optimized out>, parse_opts=<optimized out>, val_opts=0, 
    int_opts=67, parsed=0x7f4f72d80be0, lydctx_p=0x7f4f72d80bc8) at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:1116
#8  0x0000003875230513 in lyd_parse_lyb (ctx=ctx@entry=0x1d9fa30, ext=<optimized out>, parent=parent@entry=0x0, first_p=first_p@entry=0x7f4f72d80bd0, in=in@entry=0x7f4f5401d9b0, 
    parse_opts=parse_opts@entry=327680, val_opts=<optimized out>, data_type=<optimized out>, parsed=<optimized out>, lydctx_p=<optimized out>)
    at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/parser_lyb.c:1179
#9  0x000000387521c36a in lyd_parse_op_ (ctx=0x1d9fa30, ext=ext@entry=0x0, parent=parent@entry=0x0, in=0x7f4f5401d9b0, format=<optimized out>, format@entry=LYD_LYB, 
    data_type=data_type@entry=LYD_TYPE_RPC_YANG, tree=0x7f4f72d80cf0, op=0x0) at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/tree_data.c:572
#10 0x000000387521da52 in lyd_parse_op (ctx=<optimized out>, parent=parent@entry=0x0, in=<optimized out>, format=format@entry=LYD_LYB, 
    data_type=data_type@entry=LYD_TYPE_RPC_YANG, tree=tree@entry=0x7f4f72d80cf0, op=0x0) at /usr/src/debug/libyang/2.0.71+gitAUTOINC+e8e37ae07c-r0/git/src/tree_data.c:625
#11 0x000000387663b5a6 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x2705240, conn=0x1d9f820)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/shm_sub.c:3129
#12 0x000000387660e2f7 in sr_subscription_process_events (subscription=subscription@entry=0x1dc72f0, session=session@entry=0x0, stop_time_in=stop_time_in@entry=0x7f4f72d80de0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/sysrepo.c:3136
#13 0x000000387660e404 in sr_process_events (subscription=subscription@entry=0x1dc72f0, session=session@entry=0x0, stop_time_in=stop_time_in@entry=0x7f4f72d80e08)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/sysrepo.c:3190
#14 0x000000387663c484 in sr_shmsub_listen_thread (arg=0x1dc72f0) at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/shm_sub.c:3575
#15 0x0000003872c07477 in start_thread (arg=0x7f4f72d81700) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
#16 0x00000038728f23bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by michalvasko** [comment]
Okay, should work with the latest *libyang*.
