### ISSUE TITLE
SIGSEGV at edit_diff.c:2258 (with libyang2)

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#983]
yanglint 2.0.71
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.34 (SO v6.4.1)
netopeer2-server 2.0.21

Hi,

We get a SIGSEGV in libsysrepo.
Now sure what exactly triggers the issue but it happened several times.
Here's the back trace, could you please check:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000038766267e1 in sr_edit_apply_delete (edit_node=0x7f0adc01b650, next_op=<synthetic pointer>, val_equal=0, match_node=0x0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2258
2258            sr_errinfo_new(&err_info, SR_ERR_NOT_FOUND, "Node \"%s\" to be deleted does not exist.", edit_node->schema->name);
[Current thread is 1 (Thread 0x7f0aefffa700 (LWP 9968))]
(gdb) bt
#0  0x00000038766267e1 in sr_edit_apply_delete (edit_node=0x7f0adc01b650, next_op=<synthetic pointer>, val_equal=0, match_node=0x0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2258
#1  sr_edit_apply_r (first_node=0x7f0adc085b78, parent_node=0x7f0adc085b40, edit_node=edit_node@entry=0x7f0adc01b650, parent_op=<optimized out>, 
    diff_parent=diff_parent@entry=0x7f0adc087bc0, diff_root=diff_root@entry=0x7f0aefff99d8, oper_edit=0, flags=0, change=0x7f0aefff9a3c)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2355
#2  0x0000003876626ca3 in sr_edit_apply_r (first_node=0x7f0adc0875f8, parent_node=0x7f0adc0875c0, edit_node=edit_node@entry=0x7f0adc002850, parent_op=<optimized out>, 
    diff_parent=0x7f0adc087bc0, diff_parent@entry=0x7f0adc087b20, diff_root=<optimized out>, diff_root@entry=0x7f0aefff99d8, oper_edit=0, flags=0, change=0x7f0aefff9a3c)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2452
#3  0x0000003876626ca3 in sr_edit_apply_r (first_node=0x7f0adc0851e8, parent_node=0x7f0adc0851b0, edit_node=edit_node@entry=0x7f0adc002800, parent_op=<optimized out>, 
    diff_parent=0x7f0adc087b20, diff_parent@entry=0x7f0adc087a80, diff_root=<optimized out>, diff_root@entry=0x7f0aefff99d8, oper_edit=0, flags=0, change=0x7f0aefff9a3c)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2452
#4  0x0000003876626ca3 in sr_edit_apply_r (first_node=first_node@entry=0x7f0aefff9ae0, parent_node=parent_node@entry=0x0, edit_node=edit_node@entry=0x7f0adc0027b0, 
    parent_op=parent_op@entry=EDIT_CONTINUE, diff_parent=0x7f0adc087a80, diff_parent@entry=0x0, diff_root=<optimized out>, diff_root@entry=0x7f0aefff99d8, oper_edit=0, flags=0, 
    change=0x7f0aefff9a3c) at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2452
#5  0x0000003876627146 in sr_edit_mod_apply (edit=edit@entry=0x7f0adc0027b0, ly_mod=0x1561300, oper_edit=oper_edit@entry=0, data=data@entry=0x7f0aefff9ae0, 
    diff=diff@entry=0x7f0aefff9ad8, change=change@entry=0x7f0aefff9a3c) at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2497
#6  0x000000387661fc5a in sr_modinfo_edit_apply (mod_info=mod_info@entry=0x7f0aefff9ad0, edit=0x7f0adc0027b0, create_diff=create_diff@entry=1)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/modinfo.c:187
#7  0x000000387660d82b in sr_apply_changes (session=0x7f0ae800a980, timeout_ms=30000) at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/sysrepo.c:2557
#8  0x000000000040d0f4 in np2srv_rpc_editconfig_cb (session=session@entry=0x7f0adc02f100, UNUSED_sub_id=<optimized out>, UNUSED_op_path=<optimized out>, 
    input=input@entry=0x7f0adc05f2c0, event=<optimized out>, UNUSED_request_id=UNUSED_request_id@entry=1, UNUSED_output=0x7f0adc003f10, UNUSED_private_data=0x0)
    at /usr/src/debug/netopeer2-server/2.0.21+gitAUTOINC+e8bce96747-r0/git/src/netconf.c:412
#9  0x0000003876636e5c in sr_shmsub_rpc_listen_call_callback (rpc_sub=rpc_sub@entry=0x17e4360, ev_sess=0x7f0adc02f100, input_op=0x7f0adc05f2c0, event=event@entry=SR_SUB_EV_RPC, 
    request_id=request_id@entry=1, output_op=output_op@entry=0x7f0aefff9d00, err_code=0x7f0aefff9cd0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/shm_sub.c:2897
#10 0x000000387663b746 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x12e5160, conn=0x12bd820)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/shm_sub.c:3182
#11 0x000000387660e2f7 in sr_subscription_process_events (subscription=subscription@entry=0x12fa050, session=session@entry=0x0, stop_time_in=stop_time_in@entry=0x7f0aefff9de0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/sysrepo.c:3136
#12 0x000000387660e404 in sr_process_events (subscription=subscription@entry=0x12fa050, session=session@entry=0x0, stop_time_in=stop_time_in@entry=0x7f0aefff9e08)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/sysrepo.c:3190
#13 0x000000387663c484 in sr_shmsub_listen_thread (arg=0x12fa050) at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/shm_sub.c:3575
#14 0x0000003872c07477 in start_thread (arg=0x7f0aefffa700) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
#15 0x00000038728f23bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)  f 0
#0  0x00000038766267e1 in sr_edit_apply_delete (edit_node=0x7f0adc01b650, next_op=<synthetic pointer>, val_equal=0, match_node=0x0)
    at /usr/src/debug/sysrepo/2.0.34+gitAUTOINC+0f5cd41f45-r0/git/src/edit_diff.c:2258
2258            sr_errinfo_new(&err_info, SR_ERR_NOT_FOUND, "Node \"%s\" to be deleted does not exist.", edit_node->schema->name);
(gdb) p edit_node
$1 = (const struct lyd_node *) 0x7f0adc01b650
(gdb) p edit_node->schema 
$2 = (const struct lysc_node *) 0x0
(gdb)
```

**Comment by michalvasko** [comment]
Should not crash anymore.
