### ISSUE TITLE
cannot change model to get notification using TLS

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#992]
Hi,

I create a TLS listener:
```

2021-08-24 07:38:07,420 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: Resolving unresolved data nodes and their constraints...
2021-08-24 07:38:07,420 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: All data nodes and constraints resolved.
2021-08-24 07:38:07,420 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: Resolving unresolved data nodes and their constraints...
2021-08-24 07:38:07,420 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: All data nodes and constraints resolved.
2021-08-24 07:38:07,421 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: SR: Published event "done" "ietf-netconf-server" with ID 1 priority 0 for 22 subscribers.
2021-08-24 07:38:07,421 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: Resolving unresolved data nodes and their constraints...
2021-08-24 07:38:07,421 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "serverkey", but it is not required.
2021-08-24 07:38:07,422 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key[ietf-keystore:name = current()/../asymmetric-key]/ietf-keystore:certificates/ietf-keystore:certificate/ietf-keystore:name" with the value "servercert", but it is not required.
2021-08-24 07:38:07,422 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: There is no leafref "/ietf-truststore:truststore/ietf-truststore:certificates/ietf-truststore:name" with the value "cacerts", but it is not required.
2021-08-24 07:38:07,422 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: There is no leafref "/ietf-truststore:truststore/ietf-truststore:certificates/ietf-truststore:name" with the value "clientcerts", but it is not required.
2021-08-24 07:38:07,422 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LY: All data nodes and constraints resolved.
2021-08-24 07:38:07,422 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: SR: Processing "ietf-netconf-server" "done" event with ID 1 priority 0 (remaining 22 subscribers).
2021-08-24 07:38:07,423 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Listening on 0.0.0.0:6513 for TLS connections.
```

Next step is to setup a new connection, using TLS, to send a <create-subscription>. Tls connection seems accepted but the
hello message is not performed. I can see a new user is used, "client username recognized as "tls-test" but 

2021-08-24 13:48:40,491 (AbstractTransport.java:389) DEBUG : Starting to exchange the <hello> messages
2021-08-24 13:48:40,501 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Accepted a connection on 0.0.0.0:6513.
2021-08-24 13:48:40,502 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: SR: Session 5 (user "root") created.
2021-08-24 13:48:40,503 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: SR: Session 6 (user "root") created.
2021-08-24 13:48:40,503 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: SR: Session 7 (user "root") created.
2021-08-24 13:48:40,519 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: depth 1.
2021-08-24 13:48:40,519 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
2021-08-24 13:48:40,519 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
2021-08-24 13:48:40,519 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify CTN: entry with a matching fingerprint found.
2021-08-24 13:48:40,520 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify CTN: new client username recognized as "tls-test".
2021-08-24 13:48:40,520 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: depth 0.
2021-08-24 13:48:40,520 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/O=CESNET/OU=TMC/CN=example client/emailAddress=exampleclient@localhost.
2021-08-24 13:48:40,520 (Slf4jLogConsumer.java:71)  INFO : STDERR: [INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
SSL_accept timeout

2021-08-24 13:49:40,555 (Slf4jLogConsumer.java:71)  INFO : STDERR: [ERR]: LN: Client's <hello> timeout elapsed.

It seems like the hello message from server takes too much time. What is expected when using tls-test?
Am I missing something?

br,

//mike

**Comment by michalvasko** [comment]
This is not a NETCONF timeout (of hello message) but still a TLS problem, the connection is not accepted and I would blame the client side. What NETCONF client are you using?

**Comment by mpet** [comment]
Hi,

Sorry the last line was incomplete:

2021-08-24 14:15:56,631 (Slf4jLogConsumer.java:71)  INFO : STDERR: [ERR]: LN: SSL_accept timeout.

I wonder what fails in the SSL connection. The handshake is complete for TLS and it is in the data send ( under NETCONF hello) it fails. Is it possible to trace on server side?

```

Padded plaintext after DECRYPTION:  len = 80
0000: C5 9E 30 A9 C7 AB D2 B8   56 42 46 C5 20 4F 75 D4  ..0.....VBF. Ou.
0010: 01 00 80 64 B2 47 5D 2F   5A 17 C9 37 0E 90 9C 90  ...d.G]/Z..7....
0020: 37 46 19 7D A9 C8 BA 79   66 88 AF A5 98 34 F4 DD  7F.....yf....4..
0030: 91 A1 FD 8A 2A AD 81 99   9F 04 76 44 89 C5 78 0A  ....*.....vD..x.
0040: E7 80 0D 0D 0D 0D 0D 0D   0D 0D 0D 0D 0D 0D 0D 0D  ................
main, RECV TLSv1.2 ALERT:  warning, close_notify
main, called closeInternal(false)
main, SEND TLSv1.2 ALERT:  warning, description = close_notify
Padded plaintext before ENCRYPTION:  len = 80
0000: 33 C8 38 7B B4 5F 50 2F   ED 09 83 6D CA A0 4A C6  3.8.._P/...m..J.
0010: 01 00 3A 98 7D 43 D8 8A   01 AB 6B 9C C3 C1 EB C5  ..:..C....k.....
0020: BE 5F 42 92 2C 9D C7 7F   4F 1D B6 4C D0 C5 1B 9D  ._B.,...O..L....
0030: 7E AC F9 39 90 36 7E 63   E2 FA 69 76 9B 46 52 EB  ...9.6.c..iv.FR.
0040: 95 07 0D 0D 0D 0D 0D 0D   0D 0D 0D 0D 0D 0D 0D 0D  ................
main, WRITE: TLSv1.2 Alert, length = 80
[Raw write]: length = 85
0000: 15 03 03 00 50 15 75 62   30 3B 2A 25 2A CF FE 36  ....P.ub0;*%*..6
0010: 23 0C FB 49 4E 41 7C 77   34 CD 0F E4 01 71 5C 4D  #..INA.w4....q\M
0020: 2A 8E 7C B6 B8 A0 37 F1   1A BB 0A C1 89 3E 51 0C  *.....7......>Q.
0030: 1D 6F 6F 7A 72 6F 18 18   03 04 14 59 99 F8 E0 C0  .oozro.....Y....
0040: 85 94 0A A7 7B 83 BF FE   C2 99 51 C2 09 52 C8 E5  ..........Q..R..
0050: F2 AF 01 C1 86                                     .....
main, called closeSocket(false)
```

We have our own developed NETCONF client.

br,

//mike

**Comment by michalvasko** [comment]
You can debug the server but it still seems to me something is expected from the client that is not delivered. As you can see [here](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server_tls.c#L1976), only a `libssl` function is being called until it succeeds.

**Comment by mpet** [comment]
@michalvasko  I am using TLS 1.2. Is that supported?

**Comment by michalvasko** [comment]
Yes, look at the [source](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server_tls.c#L1900).

**Comment by mpet** [comment]
When I check the exception message from netopeer2 in client:
```
Caused by: java.net.SocketException: Connection closed by remote host
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1565)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.ericsson.commonlibrary.netconf.transport.AbstractBaseTransport.send(AbstractBaseTransport.java:69)

```
So it seems the socket ssl takes too long. Is there a timeout for SSL that I can set? If so where is it located?

//mike

**Comment by mpet** [comment]
One other thing. I start with ( inside docker ):
CMD ["/usr/bin/netopeer2-server", "-d", "-v2 3"]

What is needed to see ssl/tls traces on server side?

//mike

**Comment by mpet** [comment]
I checked the logs a bit more:

main, **RECV** TLSv1.2 ALERT:  warning, close_notify
main, called closeInternal(false)
main, **SEND** TLSv1.2 ALERT:  warning, description = close_notify
Padded plaintext before ENCRYPTION:  len = 80 

I interpret this as my client receives a close_notify from server. And in order tp properly shutdown the connection we should also send a close notify ( to make sure it is not a middle man attack). And we do. 

I aslo compared to oracle TLS connection log example (https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html):

"Read from the socket again to see if there is any more data. We get a close_notify message, which means this connection is shutting down properly. We send our own in turn, then close the socket."

```
[Raw read]: length = 5
0000: 15 03 01 00 12                                     .....
[Raw read]: length = 18
0000: 09 AB 95 00 43 8D C8 7C   83 18 EB C4 8C 99 43 A6  ....C.........C.
0010: 76 49                                              vI
main, READ: TLSv1 Alert, length = 18
Padded plaintext after DECRYPTION:  len = 18
0000: 01 00 FA 44 D5 57 71 5C   CC C7 D9 D0 04 23 10 D8  ...D.Wq\.....#..
0010: 21 7B                                              !.
main, RECV TLSv1 ALERT:  warning, close_notify
main, called closeInternal(false)
main, SEND TLSv1 ALERT:  warning, description = close_notify
Padded plaintext before ENCRYPTION:  len = 18
0000: 01 00 8A 2C A2 36 9C 88   22 50 6E BC 95 3B B2 C4  ...,.6.."Pn..;..
0010: FE F2                                              ..
main, WRITE: TLSv1 Alert, length = 18
[Raw write]: length = 23
0000: 15 03 01 00 12 19 BE 10   8D FA F1 CA DD AB CC 91  ................
0010: 2E 49 08 71 2B C1 05                               .I.q+..
main, called close()
main, called closeInternal(true)
main, called close()
main, called closeInternal(true)
main, called close()
main, called closeInternal(true)
```

So I would conclude the server is incorrectly sending close in TLS layer.

//mike

**Comment by michalvasko** [comment]
> Is there a timeout for SSL that I can set?

[Here](https://github.com/CESNET/libnetconf2/blob/master/src/session_server.c#L2437) is a timeout being set but it is 10 s so I do not think that is the problem.

> What is needed to see ssl/tls traces on server side?

Not sure, I do not think OpenSSL supports them. If so, please refer something I can use to add the functionality.

> So I would conclude the server is incorrectly sending close in TLS layer.

It must have a reason for doing so, probably because of the timeout it closes the connection. Look, it is possible there is a problem on the side of the server because I have tested it only with *netopeer2-cli* on the other end. However, that works correctly so I cannot really help you more. The server simply calls `SSL_accept()`, which fails, so the only thing wrong could be some TLS options, not sure what else.

**Comment by mpet** [comment]
Since whole handshake is complete there is not a problem with certs. What are the settings in model for tls? How can I find them?

**Comment by mpet** [comment]
Could you describe how you tested it with netopeer2-cli? I mean setup a tls connection and the subscribing to notifications?
If you have a log it would be very helpful.

**Comment by michalvasko** [comment]
> What are the settings in model for tls? How can I find them?

I meant some *libssl* options, there are probably some TLS options in a YANG module but they are not being used for now.

> Could you describe how you tested it with netopeer2-cli? I mean setup a tls connection and the subscribing to notifications?
If you have a log it would be very helpful.

You can try it on your own, simply set up the certificates correctly and you should be able to connect, that is what I did. There is no log because like I said, I do not think *libssl* provides any. Or you simply mean *libnetconf2*/*netopeer2* log? You can get that easily if you try it yourself, just follow the instructions for [TLS Listen](https://github.com/CESNET/Netopeer2/tree/devel#tls-listen).

**Comment by mpet** [comment]
Is it this https://www.libssh.org/ ? Which version is used?

**Comment by michalvasko** [comment]
No, *libssh* is used for SSH, for TLS [OpenSSL](https://www.openssl.org/) is used.

**Comment by mpet** [comment]
Which version?

**Comment by michalvasko** [comment]
Well, it should compile and work with "all" of them (1.x), there are some `ifdef`s in the code. I am currently using 1.1.1k.

**Comment by mpet** [comment]
ok. so if I check [code](https://github.com/CESNET/libnetconf2/blob/devel/src/session_server_tls.c#L1976)
As I understand it ( I am not used to C/C++ so bear with me) a return code is supplied from [ssl_accept](https://www.openssl.org/docs/manmaster/man3/SSL_accept.html). So now this [code2](https://github.com/CESNET/libnetconf2/blob/217bac6c212b157d6d8dd819f3f655270a035bab/src/session_server_tls.c#L1983)
And checking [ssl_get_error](https://www.openssl.org/docs/manmaster/man3/SSL_get_error.html) There seems to be many more return codes then in libnetconf2. 

That is why I get the default:

```
default:
            ERR(session, "SSL_accept failed.");
            break;
```
And I cannot really see the problem. 

Would it be possible to handle more error codes?

**Comment by michalvasko** [comment]
The only output you have posted was
```
SSL_accept timeout
```
which is not the default but actually a specific problem, as seen in the code. If you are getting the default one it can be improved.
